version: '3.3'

services:
  api:
    image: timoa/chrome-tab-rotate-server:latest@sha256:ee951b8f80dd3d33d5ec0928918848eb881886111249d9dfa274d345440d886e
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
    volumes:
      - type: bind
        source: ./config # You need to copy the config files example to the config folder at the root the project
        target: /opt/app/config
    ports:
      - 9000:9000
    restart: always

volumes:
  config:
