version: '3.3'

services:
  api:
    image: timoa/chrome-tab-rotate-server:latest@sha256:02075ab887b449e71c597c32e8001b18c4fcc1b08ecf5760bdf08bc8faf132b6
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
    volumes:
      - type: bind
        source: ./config # You need to copy the config files example to the config folder at the root the project
        target: /opt/app/config
    ports:
      - 9000:9000
    restart: always

volumes:
  config:
