version: '3.3'

services:
  api:
    image: timoa/chrome-tab-rotate-server:latest@sha256:8ab7634d706ccd63d9c1945f45725b17bc876016a98a663b19dd596ebf02ea0d
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
    volumes:
      - ./config:/opt/app/config
    ports:
      - 9000:9000
    restart: always

volumes:
  config:
