version: '3.3'

services:
  api:
    image: timoa/chrome-tab-rotate-server:latest
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
    volumes:
      - ./config:/opt/app/config
    ports:
      - 9000:9000
    restart: always

volumes:
  config:
