version: '3.3'

services:
  api:
    image: timoa/chrome-tab-rotate-server:latest@sha256:b916ac408ace2161b7d74b6382f378606c581c1693cc34b91fac72330d248722
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
    volumes:
      - ./config:/opt/app/config
    ports:
      - 9000:9000
    restart: always

volumes:
  config:
