version: '3.3'

services:
  api:
    image: timoa/chrome-tab-rotate-server:latest@sha256:58edd71fc180af7a0bdc94ae2e8d647b5ca4da059d9b09e12eb9d1864ab11c24
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
    volumes:
      - ./config:/opt/app/config
    ports:
      - 9000:9000
    restart: always

volumes:
  config:
